# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0002_address_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='addr.Address')),
            ],
        ),
    ]
