# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0004_auto_20180626_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='addr',
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
