# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0006_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='text',
            field=models.TextField(),
        ),
    ]
