# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0007_auto_20180626_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
